name: Kodi Addon-Check
on:
  # Run action when pushed to master, or for commits in a pull request.
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  kodi-addon-checker:
    name: Addon checker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kodi-version: [ leia, matrix ]
    steps:
      - name: Check out ${{ github.sha }} from repository ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install libxml2-utils
          sudo python -m pip install kodi-addon-checker

      - name: Run Addon Check for Kodi ${{matrix.kodi-version}}
        run: make check-addon-${{matrix.kodi-version}}
